### ISSUE TITLE
how to run it with zed 1? thanks

### ISSUE THREAD

**Issue by AndreV84** [stereolabs/zed-ros2-examples#11]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

--

### Use-Case

the command below won't work `
ros2 run zed_rgb_convert zed_rgb_convert`

### Anything else?

how to run?

**Comment by Myzhar** [comment]
Hi @AndreV84 
can you provide more information?
What do you expect? What do you get instead?

**Comment by AndreV84** [comment]
@Myzhar Thank you for following up
I tested this thing after getting it built
```
ros2 run zed_rgb_convert zed_rgb_convert
```
Could you extend on how to run it, please?
Here they point out that just running it won't work: https://www.stereolabs.com/docs/ros2/ros2-composition/
How it is supposed that I execute it with zed camera from the built examples?

**Comment by AndreV84** [comment]
It appears that in your readme ther are 0 instructions on use of the example in relation to how to execute it
On the other hand at the article they point out that it won't just work
```
The launch file
Starting the node using the $ ros2 run zed_rgb_convert zed_rgb_convert CLI command will result in a failure: many errors and warning will be logged in the console, while publishers and subscribers will be not linked.
```
Why won't you provide the example in a way it will just work with the supplied launch file?

**Comment by Myzhar** [comment]
@AndreV84 you can find the full explanation of this tutorial on the Stereolabs online documentation as reported in the readme.
The scope of this tutorial is to explain how to take advantage of the COMPOSITION concept in ROS2.
A simple README with command to launch the node is out of the scope of the tutorial.

If you read all the documentation, you can understand that the correct way to execute the node is not but calling it directly with the `run` command, but using the explained LAUNCH file with the correct configuration parameters.

**Comment by AndreV84** [comment]
@Myzhar, why won't you supply the correct version of the launch file in the github repository? It has a launch file supplied. Is it errorneous? copy paste from the tutorial causes formatting errors

**Comment by AndreV84** [comment]
how do you run the launch file if not using the run? these steps are not in the vague description of the article nor in the github repository

**Comment by Myzhar** [comment]
The launch file in the repository is correct and working as expected with the latest version of the ROS2 Wrapper repository and the ZED SDK v3.8

**Comment by AndreV84** [comment]
it won't run
it crashes with errors as wasa pointed out in the tutorial
how do you run the launch file if not using the run? 
could you extend, please?

**Comment by AndreV84** [comment]
I can run this thing from the examples
```
ros2 launch zed_display_rviz2 display_zed.launch.py

```
seems I can run it with
```
ros2 run zed_rgb_convert zed_rgb_convert.launch.py
```

**Comment by Myzhar** [comment]
The following "problem" has been fixed with the most recent release of the ZED ROS2 Wrapper:
`what():  intraprocess communication allowed only with volatile durability`
If you get this error then you are not using the latest versions of the ZED ROS2 repositories.
