### ISSUE TITLE
zed_node crashes on enable_obj_det service call

### ISSUE THREAD

**Issue by MHFarzaneh** [stereolabs/zed-ros2-examples#18]
Jetson AGX Xavier, running ubuntu 20, Flashed with JetPack 5.0.2
ROS2 Foxy 
ZED_SDK_Tegra_L4T35.1_v3.8.2 and ZED diagnostic is all green and 100%
Cuda version 11.4.239
ZED 2i.

When launching
`ros2 launch zed_display_rviz2 display_zed2i.launch.py`

Then in another terminal calling
`ros2 service call /zed2i/zed_node/enable_obj_det std_srvs/srv/SetBool data:\ true\ `

The ros zed node crashes with the following error
```
[zed_wrapper-3] 1674513039.665809726 [zed2i.zed_node] [INFO] Starting Object Detection
[zed_wrapper-3] 1674513039.665904705 [zed2i.zed_node] [INFO] *** Starting Object Detection ***
[zed_wrapper-3] 1674513047.599875587 [zed2i.zed_node] [INFO] Advertised on topic /zed2i/zed_node/obj_det/objects
[rviz2-1] 1674513052.449418456 [rviz2] [ERROR] InternalErrorException: Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at /tmp/binarydeb/ros-foxy-rviz-ogre-vendor-8.2.7/.obj-aarch64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 125)
[rviz2-1] terminate called after throwing an instance of 'Ogre::InternalErrorException'
[rviz2-1]   what():  InternalErrorException: Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at /tmp/binarydeb/ros-foxy-rviz-ogre-vendor-8.2.7/.obj-aarch64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 125)
[ERROR] [rviz2-1]: process has died [pid 92542, exit code -6, cmd '/opt/ros/foxy/lib/rviz2/rviz2 -d /home/aaaa/ros2_ws/install/zed_display_rviz2/share/zed_display_rviz2/rviz2/zed2i.rviz --ros-args -r __node:=zed2i_rviz2 -r __ns:=/'].
```
Sometimes it crashes right away, and sometimes after few seconds of actually detecting some objects and displaying bounding boxes in rviz.

**Comment by Myzhar** [comment]
Hi @MHFarzaneh 
the `zed_node` is not crashing, Rviz2 is crashing instead:
`[rviz2-1] 1674513052.449418456 [rviz2] [ERROR] InternalErrorException: Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at /tmp/binarydeb/ros-foxy-rviz-ogre-vendor-8.2.7/.obj-aarch64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 125)`

I suggest you search the internet for this error message to try to understand why Rviz2 is crashing.

**Comment by MHFarzaneh** [comment]
It seems to be some issue with the rviz_plugin_zed_od > ZedOdDisplay
Because if I disable this display type (Objects) in rviz2 and then enable Od, rviz2 doesn't crash.

**Comment by JWaynee** [comment]
Same issue here. 
Using regular Ubuntu 20.04, ROS2 foxy and a Dell Precision notebook.

Is there any solution to this?

**Comment by CarlDegio** [comment]
Same issue on ros foxy. Some another situation: https://answers.ros.org/question/399615/rviz2-crash/. 

But I check screenfetch and nvidia-smi, there are remaining space. So the out of memory is incomprehensible.

I recall seeing errors like this on nav2 of ros foxy (https://github.com/ros2/rviz/issues/703). It crush randomly when showing something in rviz2 and the reason is memory problem. Perhaps there are similarities between the two questions.

**Comment by Myzhar** [comment]
It's something related with NVIDIA Jetson and Ogre2. I normally suggest not running Rviz and Rviz2 on the Jetson because it's a highly demanding application that can cause random issues on an embedded device, it's preferred to execute it on a remote machine more capable.

**Comment by Myzhar** [comment]
@JWaynee what is the configuration of your Notebook, what GPU model is available?

**Comment by JWaynee** [comment]
I'm using a Quadro RTX 3000 with driver version 525.85.12, CUDA version 12.0.

**Comment by Myzhar** [comment]
OK, this is not a GPU that can go easily out of resources, but CUDA 12 can instead be a problem.
The ZED SDK does not currently support it and that can be the cause of unpredictable behaviors.

**Comment by CarlDegio** [comment]
> It's something related with NVIDIA Jetson and Ogre2. I normally suggest not running Rviz and Rviz2 on the Jetson because it's a highly demanding application that can cause random issues on an embedded device, it's preferred to execute it on a remote machine more capable.

My computer is a lenovo desktop, ubuntu20.04, ros foxy, with GTX1650, CUDA11.7. Have rviz2 crush problem when use detect but there are no valid information only `[ERROR] [rviz2-1]: process has died`.

**Comment by nsfhac** [comment]
I am having the same issue as Wayne using pretty much the same pc and version. Ubuntu 20.04, ROS2 foxy, a Dell Precision notebook, ZED SDK 3.8. CUDA version 11.7 installed from the ZED SDK itself.

**Comment by Myzhar** [comment]
I was able to replicate the issue with ROS2 Foxy, but I have not yet found a solution.
I also tried to replicate it with ROS2 Humble, but there are no problems with this version.

Can you all confirm that you are using ROS2 Foxy and not Humble?

**Comment by CarlDegio** [comment]
> I was able to replicate the issue with ROS2 Foxy, but I have not yet found a solution. I also tried to replicate it with ROS2 Humble, but there are no problems with this version.
> 
> Can you all confirm that you are using ROS2 Foxy and not Humble?

Yes. Normally Ubuntu20.04 can't install ROS2 humble. So there are problems on ROS2 especially rviz maybe.

**Comment by Myzhar** [comment]
Docker is a good solution to use ROS2 Humble even with Ubuntu 20.04.
We provide good `dockerfile` to be used to generate ROS2 Humble images ready to be used:
https://github.com/stereolabs/zed-ros2-wrapper/tree/master/docker

**Comment by CarlDegio** [comment]
OK. Thanks for your help! And I would like to know ros2 humble in docker could communicate with host ros2 foxy? even use tool like image-transport

**Comment by Myzhar** [comment]
Yes it can, the problem is that `image_transport` is not stable in Foxy, for example plugins are not working as expected:
https://github.com/stereolabs/zed-ros2-wrapper#known-issues

**Comment by JWaynee** [comment]
Yes I also use ROS2 Foxy. 
We also wrote an custom plugin for the ZED detected objects messages. This plugin worked fine until some weeks ago. When we used it today RViZ also crushed. We didn't subscribe to any images on RViZ. 
So I assume that RViZ somehow struggles with properly handling the ObjectsStamped.msg message.

**Comment by Myzhar** [comment]
I reached the same conclusion regarding the custom `ObjectsStamped` message.
Have you tried changing the middleware, trying for example to use CycloneDDS?

**Comment by zvmallol** [comment]
I'm coming across this problem. Did anyone ever find a fix to it? I followed all instructions on the Github to install, and I am using an Nvidia ORIN. rviz2 crashes after a couple seconds of object detection - and the supposedly visualized objects are never displayed on the screen.
