### ISSUE TITLE
in mapping mode, points do not decay

### ISSUE THREAD

**Issue by altineller** [stereolabs/zed-ros2-examples#23]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I turned on the mapping_enabled to true, and using 0.01 as resolution. 

### Steps to Reproduce

1.ros2 run zed_wrapper zed2i.launch
2.
3.
...

### Expected Result

when the object is no longer there, the space should not be occupied.

### Actual Result

When viewing with rviz, the if the camera captures something, and if the object moves and is no longer there, the cubes do not decay.

### ZED Camera model

ZED2i

### Environment

```shell
Ubuntu 22 on intel 64bits, with rtx2060 gpu.
```

**Comment by Myzhar** [comment]
This is not a bug, but a behavior of the Spatial Mapping module of the ZED SDK that is made to acquire static environment, not dynamic.
