### ISSUE TITLE
Correcting Stereolabs Documentation Link

### ISSUE THREAD

**Issue by lewiskaye** [stereolabs/zed-ros2-examples#24]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

On the following page: https://github.com/stereolabs/zed-ros2-examples/tree/master/tutorials/zed_depth_tutorial#readme
I have noticed the link to the StereoLabs Website contains an Underscore '_' in place of a dash '-', causing you to be taken not to the documentation, but rather the store.  

### Steps to Reproduce

1. Click Link
2. Go to wrong page
3.
...

### Expected Result

Go to Documentation Site

### Actual Result

Go to Store Site

### ZED Camera model

ZED2i

### Environment

```shell
N/A
```

**Comment by Myzhar** [comment]
Thank you for reporting. Fixed
