### ISSUE TITLE
Cannot open multiple camera's using zed_multi_camera.launch.py

### ISSUE THREAD

**Issue by JHeuverRiwo** [stereolabs/zed-ros2-examples#25]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Cannot open multiple camera's using zed_multi_camera.launch.py:
We run a ZED-Box Orin, have two ZED-X mini's attached using the GSML lines, and want to use both. We are on ROS2 Foxy on the ZED-Box since it is Tier one with Ubuntu 20.04.
I try to launch the cameras using: 
```
$ ros2 launch zed_multi_camera zed_multi_camera.launch.py cam_names:='[zed_left,zed_right]' cam_models:='[zedxm,zedxm]' cam_serials:='[SERIAL_1,SERIAL_2]' cam_poses:=[[0.0,0.0,0.0,0.0,0.0,0.0],[0.0,0.0,0.1,0.0,0.0,0.5]]
```
And the  program crashes due to it timing out connecting to at least one of the cameras. Cameras are up and running when using the Depth viewer tool

### Steps to Reproduce

1. have ZED-Box orin installed with ROS2 Foxy, stock otherwise.
2. Clone, install deps using rosdep, build and source zed_ros2_wrapper and zed_ros2_examples.
3. Connect two cameras on the GSML lines. Make sure they are reachable using for instance the depth viewer
4. run ```$ ros2 launch zed_multi_camera zed_multi_camera.launch.py cam_names:='[zed_left,zed_right]' cam_models:='[zedxm,zedxm]' cam_serials:='[SERIAL_1,SERIAL_2]' cam_poses:=[[0.0,0.0,0.0,0.0,0.0,0.0],[0.0,0.0,0.1,0.0,0.0,0.5]]``` where the serial numbers are the serial numbers of the two particular cameras.
5. program crashes due to time out connecting to (one of the) cams.

### Expected Result

Both cameras are launched properly.

### Actual Result

Seemingly relevant error messages:
[zed_wrapper-2] [ZED][ERROR] [ZED] sl::Camera::Open has not been called, no Camera instance running.
[zed_wrapper-2] [WARN] [1689929992.324157945] [zed_left.zed_node_0]: Error opening camera: CAMERA NOT DETECTED
[zed_wrapper-2] [INFO] [1689929992.324295070] [zed_left.zed_node_0]: Please verify the camera connection
[zed_wrapper-2] [ERROR] [1689929992.324323999] [zed_left.zed_node_0]: Camera detection timeout

### ZED Camera model

ZED

### Environment

```shell
System: ZED-Box Orin
OS: Ubuntu 20.04 variant installed with the Orin.
ROS2 Distro: Foxy
Cam (drop down lacks the option we use): ZED-X mini.
```

**Comment by Myzhar** [comment]
Bug fixed with the latest versions of the ZED SDK

**Comment by immanueln98** [comment]
Hi @Myzhar 

I am facing the same issue when trying to open one ZedX camera and three ZEDXOneGS cameras. The 3 ones open sucessfully but the ZEDX camera returns failed to open. 

However, when opening the ZEDX by itself via the wrapper, it opens successfully. My guess is that it could be due to the ZEDX requiring more CUDA cores/memory? I could be wrong.

Your help will be much appreciated

**Comment by immanueln98** [comment]
Yes I am, I updated everything before trying it out

**Comment by Myzhar** [comment]
@immanueln98 please write me an email to support@stereolabs.com
Add the `dmesg.log` file generated by the command `sudo ZED_Diagnostic --dmesg`
