### ISSUE TITLE
Link to Aruco example gives a 404

### ISSUE THREAD

**Issue by alfem** [stereolabs/zed-ros2-examples#30]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Readme in this repository shows a list of examples, but the Aruco one points to a inexistant page:

https://github.com/stereolabs/zed-ros2-examples/blob/master/zed_aruco_localization

### Steps to Reproduce

1. Visit the main page of this repository
2. Scroll down to Examples section
3. Click on [ZED Localization with ArUco markers]
4.
5.
...

### Expected Result

A page with info about this code example

### Actual Result

A 404, not found, page.

### ZED Camera model

ZED2

### Environment

```shell
Does not matter.
```

**Comment by Myzhar** [comment]
Fixed in commit 534543220d92e2d5df3c9d2ad43f89d53b6e4693
