### ISSUE TITLE
Zed 2 Multi Camera Example for ROS2

### ISSUE THREAD

**Issue by sisaha9** [stereolabs/zed-ros2-examples#9]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Something similar to https://github.com/stereolabs/zed-ros-examples/issues/8 but for ROS2

### Use-Case

Running multiple Zed cameras using ROS2

### Anything else?

I tried what was stated in that other launch file and provided separate camera_id but I could only see one of them. The other one never connects. This was on ROS2 Galactic (with image_commons 3.0.0 and fix suggested here https://github.com/stereolabs/zed-ros2-wrapper/issues/79#issuecomment-1050744806). I have 2 Zed cameras connected to 2 separate USB ports on my computer with Quadro RTX 3000 and 6 GB of memory. This is also running on a custom Dockerfile I have that is based off of nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04

**Comment by sisaha9** [comment]
I renamed to zed_id (based off code) and added serial_number too. This made it more stable. I realize now that a successful launch depends on how my machine detects the Zed 2. A successful `lsusb` output looks like below

```bash
Bus 002 Device 072: ID 2b03:f780 Technologies, Inc. ZED 2
Bus 002 Device 071: ID 2b03:f780 Technologies, Inc. ZED 2
```

But usually one of these won't be detected as ZED 2 and instead as some keyboard. Is there a way to better stabilize this?

**Comment by wuxiaohua1011** [comment]
+1

**Comment by s183898** [comment]
Can you re-open this? I have a similar issue, as I can't get two ZED 2i to work on ROS2 foxy at the same time.

**Comment by Myzhar** [comment]
Please open a new issue adding all the required information and eventually tagging this one if needed.
